- id: '1657894966012'
  alias: 'Office: Subwoofer Sync With Home Theater'
  description: Power On SubWoofer When Marantz Turns On and vice versa
  trigger:
  - platform: device
    device_id: 2cb05ea25c946bf67aaab462a36a5ba2
    domain: media_player
    entity_id: media_player.marantz_sr5011
    type: turned_on
    id: HT_ON
  - platform: device
    device_id: 2cb05ea25c946bf67aaab462a36a5ba2
    domain: media_player
    entity_id: media_player.marantz_sr5011
    type: turned_off
    id: HT_OFF
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: HT_ON
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          device_id: 86db6e60ff14c3daf2aa2ee9113f7d34
    - conditions:
      - condition: trigger
        id: HT_OFF
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          device_id: 86db6e60ff14c3daf2aa2ee9113f7d34
  mode: single
- id: '1658353178227'
  alias: 'Office: SubWoof Post Power-Restore State'
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 86db6e60ff14c3daf2aa2ee9113f7d34
    entity_id: switch.h103_subwoof
    domain: switch
  mode: single
- id: '1658793243219'
  alias: Set SimpliSafe at Night
  description: Arm SimpliSafe alarm to Home mode if either Lindsay or Stephen Device
    presence detected
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: or
    conditions:
    - condition: device
      device_id: 73c12d1fa67caf9f2d89703a48ec3625
      domain: device_tracker
      entity_id: device_tracker.amos_iphone
      type: is_home
    - condition: device
      device_id: 52e6447a2cde2fcd56002fa96e122777
      domain: device_tracker
      entity_id: device_tracker.lindsays_iphone
      type: is_home
  action:
  - device_id: 65a8e8d2ed76c3e82bdf91ea161c5628
    domain: alarm_control_panel
    entity_id: alarm_control_panel.4216_victoria_dr_alarm_control_panel_alarm_control_panel
    type: arm_home
  mode: single
- id: '1661019086429'
  alias: 'Schedule: Mushroom Grow Light'
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
    id: SunUp
  - platform: sun
    event: sunset
    offset: 0
    id: SunDown
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: SunUp
      sequence:
      - type: turn_on
        device_id: 74db76f01d47eb0d5ee0172843cef94b
        entity_id: switch.shellyplugus_083af20077a4_switch_0
        domain: switch
    - conditions:
      - condition: trigger
        id: SunDown
      sequence:
      - type: turn_off
        device_id: 74db76f01d47eb0d5ee0172843cef94b
        entity_id: switch.shellyplugus_083af20077a4_switch_0
        domain: switch
  mode: single
- id: '1661712457366'
  alias: 'Schedule: Outdoor Lights'
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30
    alias: When the sun sets offset by 30
    id: SunUp
  - platform: sun
    event: sunset
    offset: '-30'
    id: SunDown
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: SunUp
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.outdoor_lights
    - conditions:
      - condition: trigger
        id: SunDown
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.outdoor_lights
  mode: single
- id: '1673286341891'
  alias: Dehumidifier Power
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 098e716c72ce23dc1b3b9c034c10396a
    entity_id: sensor.basement_thermohygrometer_humidity
    domain: sensor
    above: 45
    id: Basement Damp
  - type: humidity
    platform: device
    device_id: 098e716c72ce23dc1b3b9c034c10396a
    entity_id: sensor.basement_thermohygrometer_humidity
    domain: sensor
    below: 35
    id: Basement Dry
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Basement Damp
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.tasmota
    - conditions:
      - condition: trigger
        id: Basement Dry
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.tasmota
  mode: single
- id: '1673286578742'
  alias: 'Notifications: ThermoHygrometer Low Battery Warning'
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: or
    conditions:
    - type: is_battery_level
      condition: device
      device_id: 1cb3e02eb08292e277f6b2997f995485
      entity_id: sensor.guest_room_thermohygrometer_battery
      domain: sensor
      below: 10
    - type: is_battery_level
      condition: device
      device_id: 1cb3e02eb08292e277f6b2997f995485
      entity_id: sensor.guest_room_thermohygrometer_battery
      domain: sensor
      below: 10
  action:
  - service: notify.mobile_app_amos_iphone
    data:
      message: Govee ThermoHygrometer Battery is below 10%. Replace batteries soon!
      title: Low Battery Warning
  mode: single
- id: '1673891966542'
  alias: 'Notifications: Ping TV'
  description: ''
  trigger:
  - platform: device
    device_id: 0351bd840216c9f2a38a2e9490dbc19e
    domain: media_player
    entity_id: media_player.family_room_lgtv
    type: turned_on
  condition: []
  action:
  - service: notify.family_room_lgtv
    data:
      message: I love you!
  mode: single
- id: '1674314800351'
  alias: 'Laundry: Washing Machine Status'
  description: Logic to determine current status of washing machine based on power
    output of device
  trigger:
  - platform: numeric_state
    entity_id: sensor.s31_3_washing_machine_energy_power
    for:
      hours: 0
      minutes: 3
      seconds: 0
    id: 'Off'
    below: 3
  - platform: numeric_state
    entity_id: sensor.s31_3_washing_machine_energy_power
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: Idling
    below: 10
    above: 3
  - platform: numeric_state
    entity_id: sensor.s31_3_washing_machine_energy_power
    id: Running
    above: 10
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'Off'
      sequence:
      - service: input_select.select_option
        data:
          option: 'Off'
        target:
          entity_id: input_select.washing_machine_status
    - conditions:
      - condition: trigger
        id: Idling
      sequence:
      - service: input_select.select_option
        data:
          option: Idling
        target:
          entity_id: input_select.washing_machine_status
    - conditions:
      - condition: trigger
        id: Running
      sequence:
      - service: input_select.select_option
        data:
          option: Running
        target:
          entity_id: input_select.washing_machine_status
  mode: single
- id: '1674347490136'
  alias: Turn on Hall Lamp
  description: Turns on Hall Lamp with Sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_on
    device_id: 61eff37a3d2100574c121b7821b24a1d
    entity_id: switch.tasmota_2
    domain: switch
  mode: single
- id: '1674347540321'
  alias: 'Home: Goodnight Routine'
  description: Turns off lights when Alarm is armed to Home mode
  trigger:
  - platform: device
    device_id: 65a8e8d2ed76c3e82bdf91ea161c5628
    domain: alarm_control_panel
    entity_id: alarm_control_panel.4216_victoria_dr_alarm_control_panel_alarm_control_panel
    type: armed_home
  condition: []
  action:
  - type: turn_off
    device_id: 61eff37a3d2100574c121b7821b24a1d
    entity_id: switch.tasmota_2
    domain: switch
  - type: turn_off
    device_id: ede4b533a6dab86ba81173d2f6e07c28
    entity_id: switch.family_room_sound_bar
    domain: switch
  - type: turn_off
    device_id: c0fb3096102393970e54c3e0ad087a9a
    entity_id: switch.dining_room_shelf_lights
    domain: switch
  mode: single
- id: '1674405833015'
  alias: 'Laundry: Washing Machine Completed Notification'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.washing_machine_status
    to: 'Off'
  condition: []
  action:
  - service: notify.mobile_app_amos_iphone
    data:
      message: Washing Machine done and ready to be emptied!
      title: Laundry Room
  - if:
    - condition: state
      entity_id: media_player.family_room_lgtv
      state: 'off'
    then: []
    else:
    - service: notify.family_room_lgtv
      data:
        message: Washing machine is finished!
  - service: notify.mobile_app_lindsays_iphone
    data:
      message: Washing Machine complete and ready to be emptied!
      title: Laundry Room
  mode: single
- id: '1674418857081'
  alias: Home Status Logic
  description: Logic to determine current status of home based on occupancy and alarm
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.4216_victoria_dr_alarm_control_panel_alarm_control_panel
    to: armed_home
    id: Night
  - platform: numeric_state
    entity_id: zone.home
    attribute: persons
    above: 0
    id: Home
  - platform: numeric_state
    entity_id: zone.home
    attribute: persons
    below: 1
    id: Away
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Night
      sequence:
      - service: input_select.select_option
        data:
          option: Night
        target:
          entity_id: input_select.house_status
    - conditions:
      - condition: trigger
        id: Home
      sequence:
      - service: input_select.select_option
        data:
          option: Home
        target:
          entity_id: input_select.house_status
    - conditions:
      - condition: trigger
        id: Away
      sequence:
      - service: input_select.select_option
        data:
          option: Away
        target:
          entity_id: input_select.house_status
  mode: single
- id: '1674420171955'
  alias: House Status Actions
  description: What happens when we all come and go from the house
  trigger:
  - platform: state
    entity_id:
    - input_select.house_status
    to: Away
    id: Away
  - platform: state
    entity_id:
    - input_select.house_status
    to: Home
    id: Home
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Away
      sequence:
      - service: climate.set_preset_mode
        data:
          preset_mode: away
        target:
          entity_id:
          - climate.master_bedroom_heater
          - climate.guest_room
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.all_lights
    - conditions:
      - condition: trigger
        id: Home
      sequence:
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        target:
          entity_id:
          - climate.master_bedroom_heater
          - climate.guest_room
  mode: single
- id: '1674421594354'
  alias: Notifications Test Lab
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_amos_iphone
    data:
      title: Washing Done
      message: Your washing is ready
      data:
        actions:
        - action: REMIND30
          title: Remind me in 30mins
          icon: sfsymbols:clock
        - action: WASHER_EMPTIED
          title: Emptied Washing Machine
          icon: sfsymbols:drop.circle
          destructive: true
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: REMIND30
    timeout:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - service: notify.mobile_app_amos_iphone
    data:
      message: will remind you again in 30mins to get laundry
  mode: single
- id: '1674435262405'
  alias: 'Utilities: Hot Water Boost'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.hot_water_boost
  condition: []
  action:
  - service: water_heater.set_operation_mode
    data:
      operation_mode: high_demand
    target:
      entity_id: water_heater.heat_pump_water_heater
  - service: notify.mobile_app_amos_iphone
    data:
      message: Boost mode activated for 1hr
      title: Water Heater
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: water_heater.set_operation_mode
    data:
      operation_mode: heat_pump
    target:
      entity_id: water_heater.heat_pump_water_heater
  mode: single
- id: '1674438847978'
  alias: 'Utilities: Water Heater Boost Helper Toggle'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - water_heater.heat_pump_water_heater
    attribute: operation_mode
    to: high_demand
    id: to_boost
  - platform: state
    entity_id:
    - water_heater.heat_pump_water_heater
    to: heat_pump
    id: to_normal
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: to_boost
      sequence:
      - service: input_boolean.turn_on
        data: {}
    - conditions:
      - condition: trigger
        id: to_normal
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.water_heater_boost_mode_helper
  mode: single
