# Guest Room thermostat
- platform: generic_thermostat
  unique_id: guest_room_thermostat
  name: Guest Room AC
  heater: switch.guest_ac
  #switch.guest_ac
  target_sensor: sensor.guest_room_thermohygrometer_temperature
  min_temp: 66
  max_temp: 80
  initial_hvac_mode: "off"
  min_cycle_duration:
    minutes: 10
  target_temp: 72
  away_temp: 66
  cold_tolerance: 0.5
  hot_tolerance: 0.5
  ac_mode: false
  precision: 1

# Master Bedroom thermostat
- platform: generic_thermostat
  unique_id: master_bedroom_thermostat
  name: Master Bedroom Heater
  heater: switch.shelly1pm_master_bedroom
  target_sensor: sensor.master_bedroom_thermohygrometer_temperature
  min_temp: 65
  max_temp: 80
  initial_hvac_mode: "off"
  min_cycle_duration:
    minutes: 10
  target_temp: 67
  away_temp: 60
  cold_tolerance: 0.5
  hot_tolerance: 0.5
  ac_mode: false
  precision: 1