# Includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
climate: !include climate.yaml
template: !include templates.yaml
alert: !include alerts.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# MariaDB
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30
  commit_interval: 1
#  exclude:
#    entities:
#      none yet!

history:

homekit:
  filter:
    include_entities:
      - switch.amcrest_camera_privacy_mode

influxdb:
  host: 192.168.1.100
  port: 8086
  database: homeassistant
  username: stephengarden
  password: !secret influxdb_pw
  max_retries: 3
  default_measurement: state
  include:
    entity_globs:
      - sensor.sump_pump*
      - sensor.openweathermap*

conversation:
  intents:
    SetTimer:
      - "Set a timer for {duration}"
    CancelTimer:
      - "Cancel the timer"

amcrest:
  - host: 192.168.1.72
    username: admin
    password: M4rbj9fHhd
    switches:
      - privacy_mode

timer:
  undercabinet_vacuum:
    duration: "00:00:20"

input_datetime:
  sump_pump_last_started:
    name: "Sump Pump Time Started"
    has_time: true
    has_date: true
    icon: mdi:clock